/*
 * AUTO-GENERATED FILE.
 * Do not edit this file manually.
 * Generated by scripts/generate-build-info.mjs
 */

export const BUILD_INFO = {
  build: '2026.07.19.9',
  generatedAt: '2026-07-19T12:00:01.879Z'
} as const;
