/*
 * AUTO-GENERATED FILE.
 * Do not edit this file manually.
 * Generated by scripts/generate-build-info.mjs
 */

export const BUILD_INFO = {
  build: '2026.07.30.7',
  generatedAt: '2026-07-30T16:53:42.635Z'
} as const;
